### ISSUE TITLE
[testing/new] Use Google Test framework

### ISSUE THREAD

**Issue by pietrik123** [pietrik123/untitled-sdl-tank-game#19]
Set up Google Test framework for use in the project. Probably it requires new version of MS Visual Studio 17. Please update readme.md file or create a page in project's Wiki here on Github: this should show how to configure the project, so that it can use Google Test (what version of MS VS should be used and what kind of configuration). 
Please add example test case, so that we could try locally if the test compiles and executes. Could be just an example one like this:

```
EXPECT_EQ(1,1);
```

**Comment by dante7867** [comment]
finished
