### ISSUE TITLE
[new] create new algorithm for `Enemy`

### ISSUE THREAD

**Issue by pietrik123** [pietrik123/untitled-sdl-tank-game#33]
Create a new AI for the enemy. You may create a new class (deriving from `Enemy`), which contains new movement method.
Please use `Enemy::follow()` as reference.
A new algorithm may look like this:

```
if (player is close) 
{
    follow_player()
}
else
{
    patrol_area()
}

patrol_area()
{
    while (true)
    {
        go(pointA)
        go(pointB)
    }
}
```

Please add a new `Enemy` object to the `Game` instance and test how it works.

**Comment by dante7867** [comment]
done
