### ISSUE TITLE
Create header file with constants

### ISSUE THREAD

**Issue by pietrik123** [pietrik123/untitled-sdl-tank-game#40]
Let's move some constant values to a separate file (such as game_settings.h). For example in `Enemy`or `Player` the `displcmnt` field or `maxEnergy`. Also damage done by enemies' hit can be put in such file. Source file will have to include the file. Also in file Game.h:
```cpp
#define SCREEN_WIDTH  640
#define SCREEN_HEIGHT  480

#define BULLET_LIFE 15
#define FLAME_LIFE 15
```
... can be replaced by constants.

**Comment by dante7867** [comment]
implemented
